apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-database
  namespace: exam
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: mysql-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-backend
  namespace: exam
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-frontend
  namespace: exam
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend-service